// export const baseUrl = "https://ams-server-kjc1.onrender.com";
export const baseUrl = "http://localhost:5000";

export const coachTitles = [
  "Assistant Coach",
  "Associate Head Coach",
  "Offensive Coordinator",
  "Defensive Coordinator",
  "Special Teams Coach",
  "Position Coach",
  "Strength and Conditioning Coach",
  "Goalkeeper Coach",
  "Head Coach Emeritus",
  "Head Athletic Trainer",
  "Scouting Director",
  "Recruiting Coordinator",
  "Consultant Coach",
  "Video Analyst",
  "Performance Psychologist",
  "Nutritionist/Dietitian",
  "Player Development Coach",
  "Academic Advisor",
  "Life Coach/Mentor",
  "Assistant to the Head Coach",
  "Strength and Conditioning Coordinator",
  "Technical Director",
  "Tactical Analyst",
  "Performance Analyst",
  "Rehabilitation Specialist",
  "Sports Scientist",
  "Developmental Coach",
  "Volunteer Coach",
  "Head Coach's Personal Assistant",
  "Motivational Coach",
  "Game Management Coach",
];
